name: Sync to Hugging Face Hub
on:
  push:
    branches: [main, master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          git branch -M main
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-sync from GitHub"
          git remote add origin "https://mrmayankmathur:$HF_TOKEN@huggingface.co/spaces/mrmayankmathur/gan-hemt-solver-backend"
          git push --force origin main
